name: 'Check CLI version from package.json'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/authorizer/**'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kriasoft/check-version@v1
        with: { path: 'packages/authorizer' }
