name: 'Publish package into NPM registry'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check_run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check run'
        env:
          githubEventName: ${{ github.event_name }}
          githubEventPath: ${{ github.event_path }}
        run: |
          echo "githubEventName: $githubEventName"
          echo "githubEventPath: $githubEventPath"

  deploy_sites:
    uses: ./.github/workflows/package.yml
    with:
      package: sites-graphql
    secrets:
      token: este es mi doppler token dev
  deploy_authorizer:
    uses: ./.github/workflows/package.yml
    with:
      package: authorizer
    secrets:
      token: este es mi doppler token dev