name: 'Release'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  define-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.define.outputs.environment }}
    steps:
      - name: Define Environment
        id: define
        run: |
          if [[ $GITHUB_REF == *"main"* ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "Environment is production"
          else
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "Environment is development"
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

  show-environment:
    needs: define-environment
    runs-on: ubuntu-latest
    steps:
      - name: Show Environment
        run: |
          echo "Environment is $SETTED_ENVIRONMENT"
        env:
          SETTED_ENVIRONMENT: ${{ needs.define-environment.outputs.environment }}
  
  deploy_sites:
    needs: [define-environment]
    uses: ./.github/workflows/package.yml
    with:
      package: sites-graphql
      enviroment: ${{ needs.define-environment.outputs.environment }}
    secrets: inherit

  deploy_authorizer:
    needs: [define-environment]
    uses: ./.github/workflows/package.yml
    with:
      package: authorizer
      enviroment: ${{ needs.define-environment.outputs.environment }}
    secrets: inherit