name: 'Release'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_sites:
    uses: ./.github/workflows/package.yml
    with:
      package: sites-graphql
      enviroment: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') && 'production' || 'development' }}
    secrets: inherit

  deploy_authorizer:
    uses: ./.github/workflows/package.yml
    with:
      package: authorizer
      enviroment: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') && 'production' || 'development' }}
    secrets: inherit