name: 'Deploy sites-graphql'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./reusable-workflow.yml@main
    with:
      package: sites-graphql
    secrets:
      token: este es mi doppler token dev