name: Reusable package deployer

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOPPLER_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      PACKAGE: ${{ inputs.package }}
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: 'Publish'
        run: |
          echo "Publishing $PACKAGE ..."
          echo $DOPPLER_TOKEN
          echo $ENVIRONMENT
      - name: Dump DOPPLER_TOKEN
        run: |
          echo DOPPLER_TOKEN is $DOPPLER_TOKEN
          if [[ $DOPPLER_TOKEN == *"PROD"* ]]; then
            echo "This is the PROD DOPPLER_TOKEN!"
          else
            echo "This is NOT the PROD DOPPLER_TOKEN!"
          fi
