name: 'Deploy sites-graphql'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/package.yml
    with:
      package: sites-graphql
    secrets:
      token: este es mi doppler token dev