name: 'Deploy authorizer'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/package.yml
    with:
      package: authorizer
      enviroment: development
    secrets: inherit