name: Reusable package deployer

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      enviroment:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOPPLER_TOKEN: ${{ secrets.token }}
      PACKAGE: ${{ inputs.package }}
      ENVIROMENT: ${{ inputs.enviroment }}
    steps:
      - name: 'Publish'
        run: |
          echo "Publishing $PACKAGE ..."
          echo $DOPPLER_TOKEN
          echo $ENVIROMENT
