name: 'Deploy sites-graphql package'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/sites-graphql/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      DOPPLER_TOKEN: "este es mi doppler token dev"
    steps:
      - name: 'Publish'
        run: |
          echo "Publishing sites-graphql ..."
          echo $DOPPLER_TOKEN