name: 'Deploy authorizer'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./reusable-workflow.yml
    with:
      package: authorizer
    secrets:
      token: este es mi doppler token dev