name: release-please

on:
  push:
    branches:
      - main
    paths:
      - packages/authorizer/**

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
      - run: ls -a packages
      - run: ls -a packages/authorizer
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          monorepo-tags: true
          path: packages/authorizer
      - run: echo "PUBLISHING"
        if: ${{ steps.release.outputs.release_created }}
        
permissions:
  contents: write
  pull-requests: write